version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: US/Eastern
  open-pull-requests-limit: 10
  reviewers:
  - djdmbrwsk
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
