version: '3.7'
services:
  ts-service-boilerplate:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - .:/app:delegated
      - /app/node_modules
    command: npm start
    # command: npm run watch
